In [1]:
import sys 
sys.path.append("../")

In [3]:
import pandas as pd 
import datetime as dt
import plotly.graph_objects as go 
from technical.indicators import RSI
from technical.patterns import apply_patterns
from plotting import CandlePlot

In [4]:
df_raw = pd.read_pickle("../data/EUR_USD_H1.pkl")

In [5]:
df_raw.shape

(59621, 14)

In [6]:
df_an = df_raw.copy()#df_raw.iloc[-6000:].copy()
df_an.reset_index(drop=True, inplace=True)

In [7]:
df_an.shape

(59621, 14)

In [8]:
df_an = RSI(df_an)
df_an.head()

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,RSI_14
0,2015-06-01 00:00:00+00:00,1195,1.09573,1.09628,1.09346,1.09424,1.09565,1.09620,1.09337,1.09415,1.09581,1.09636,1.09355,1.09433,NaN
1,2015-06-01 01:00:00+00:00,922,1.09424,1.09473,1.09305,1.09420,1.09416,1.09465,1.09297,1.09412,1.09433,1.09481,1.09313,1.09427,NaN
2,2015-06-01 02:00:00+00:00,656,1.09418,1.09540,1.09404,1.09509,1.09409,1.09531,1.09395,1.09501,1.09426,1.09549,1.09412,1.09517,NaN
3,2015-06-01 03:00:00+00:00,443,1.09506,1.09556,1.09481,1.09502,1.09498,1.09549,1.09473,1.09495,1.09513,1.09564,1.09489,1.09509,NaN
4,2015-06-01 04:00:00+00:00,813,1.09498,1.09652,1.09491,1.09598,1.09491,1.09644,1.09484,1.09590,1.09505,1.09659,1.09498,1.09605,NaN

In [9]:
df_an = apply_patterns(df_an)

In [39]:
df_an["EMA_50"] = df_an.mid_c.ewm(span=50, min_periods=50).mean()

In [40]:
df_an.columns

Index(['time', 'volume', 'mid_o', 'mid_h', 'mid_l', 'mid_c', 'bid_o', 'bid_h',
       'bid_l', 'bid_c', 'ask_o', 'ask_h', 'ask_l', 'ask_c', 'RSI_14',
       'body_lower', 'body_upper', 'body_bottom_perc', 'body_top_perc',
       'body_perc', 'direction', 'body_size', 'low_change', 'high_change',
       'body_size_change', 'mid_point', 'mid_point_prev_2', 'body_size_prev',
       'direction_prev', 'direction_prev_2', 'body_perc_prev',
       'body_perc_prev_2', 'HANGING_MAN', 'SHOOTING_STAR', 'SPINNING_TOP',
       'MARUBOZU', 'ENGULFING', 'TWEEZER_TOP', 'TWEEZER_BOTTOM',
       'MORNING_STAR', 'EVENING_STAR', 'EMA_200', 'EMA_50'],
      dtype='object')

In [42]:
our_cols= ["time",'mid_o', 'mid_h', 'mid_l', 'mid_c','bid_o', 'bid_h',
       'bid_l', 'bid_c', 'ask_o', 'ask_h', 'ask_l', 'ask_c', "ENGULFING", 'direction', 'EMA_50', "RSI_14"]

In [43]:
df_slim = df_an[our_cols].copy()
df_slim.dropna(inplace=True)
df_slim.reset_index(drop=True, inplace=True)

In [44]:
df_slim.head()

,time,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,ENGULFING,direction,EMA_50,RSI_14
0,2015-06-03 01:00:00+00:00,1.11432,1.11754,1.11416,1.11745,1.11422,1.11746,1.11408,1.11738,1.11441,1.11762,1.11423,1.11752,True,1,1.104606,76.638276
1,2015-06-03 02:00:00+00:00,1.11742,1.11746,1.11544,1.11598,1.11734,1.11738,1.11536,1.11591,1.11750,1.11753,1.11552,1.11605,False,-1,1.105119,70.803715
2,2015-06-03 03:00:00+00:00,1.11595,1.11616,1.11520,1.11568,1.11588,1.11609,1.11511,1.11562,1.11602,1.11625,1.11527,1.11575,False,-1,1.105592,69.638514
3,2015-06-03 04:00:00+00:00,1.11568,1.11738,1.11556,1.11627,1.11561,1.11730,1.11549,1.11620,1.11575,1.11745,1.11563,1.11634,True,1,1.106068,70.661109
4,2015-06-03 05:00:00+00:00,1.11624,1.11882,1.11618,1.11758,1.11616,1.11873,1.11610,1.11751,1.11631,1.11890,1.11625,1.11765,False,1,1.106578,72.847811

In [47]:
BUY = 1 
SELL = -1 
NONE = 0
RSI_LIMIT = 50.0 

def apply_signal(row):
    if row.ENGULFING == True:
        if row.direction == BUY and row.mid_l > row.EMA_50:
            if row.RSI_14 > RSI_LIMIT:
                return BUY 
        if row.direction == SELL and row.mid_h < row.EMA_50:
            if row.RSI_14 < RSI_LIMIT:
                return SELL
    return NONE

In [48]:
df_slim["SIGNAL"] = df_slim.apply(apply_signal, axis=1)

In [49]:
df_slim["SIGNAL"].value_counts()

SIGNAL
 0    54016
-1     2832
 1     2724
Name: count, dtype: int64

In [50]:
LOSS_FACTOR = -1.0 
PROFIT_FACTOR = 2.0

def apply_take_profit(row):
    if row.SIGNAL != NONE: 
        if row.SIGNAL == BUY:
            return(row.ask_c - row.ask_o) * PROFIT_FACTOR + row.ask_c
        else: 
            return(row.bid_c - row.bid_o) * PROFIT_FACTOR + row.bid_c
    else: 
        return 0.0 
    
def apply_stop_loss(row):
    if row.SIGNAL != NONE:
        if row.SIGNAL == BUY:
            return row.ask_o
        else: 
            return row.bid_o
    else: 
        return 0.0

In [51]:
df_slim["TP"] = df_slim.apply(apply_take_profit, axis=1)
df_slim["SL"] = df_slim.apply(apply_stop_loss, axis=1)

In [52]:
df_slim[df_slim.SIGNAL==BUY].head()

,time,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,ENGULFING,direction,EMA_50,RSI_14,SIGNAL,TP,SL
0,2015-06-03 01:00:00+00:00,1.11432,1.11754,1.11416,1.11745,1.11422,1.11746,1.11408,1.11738,1.11441,1.11762,1.11423,1.11752,True,1,1.104606,76.638276,1,1.12374,1.11441
3,2015-06-03 04:00:00+00:00,1.11568,1.11738,1.11556,1.11627,1.11561,1.11730,1.11549,1.11620,1.11575,1.11745,1.11563,1.11634,True,1,1.106068,70.661109,1,1.11752,1.11575
25,2015-06-04 02:00:00+00:00,1.12596,1.12691,1.12578,1.12660,1.12588,1.12684,1.12570,1.12653,1.12603,1.12700,1.12584,1.12666,True,1,1.116362,68.101812,1,1.12792,1.12603
39,2015-06-04 16:00:00+00:00,1.12696,1.13184,1.12608,1.12878,1.12686,1.13175,1.12601,1.12869,1.12705,1.13202,1.12616,1.12887,True,1,1.122071,55.399618,1,1.13251,1.12705
100,2015-06-09 05:00:00+00:00,1.13108,1.13459,1.13106,1.13394,1.13101,1.13450,1.13099,1.13385,1.13114,1.13469,1.13112,1.13403,True,1,1.122144,76.308939,1,1.13981,1.13114

In [53]:
df_plot = df_slim.iloc[0:100]
cp = CandlePlot(df_plot, candles=True)

trades = cp.df_plot[cp.df_plot.SIGNAL != NONE]
markers = ["mid_c", "TP", "SL"]
marker_colors = ["#0000FF", "#00FF00", "#FF0000"]

for i in range(3):
    cp.fig.add_trace(go.Scatter(
        x = trades.sTime,
        y = trades[markers[i]],
        mode = "markers",
        marker=dict(color=marker_colors[i],size=12)
    ))

cp.show_plot(line_traces=["EMA_50"], sec_traces=["RSI_14"], height=250)

In [54]:
class Trade:
    def __init__(self, row):
        self.running = True
        self.start_index = row.name

        if row.SIGNAL == BUY:
            self.start_price = row.ask_c
            self.end_price = row.ask_c 
        else:
            self.start_price = row.bid_c
            self.end_price = row.bid_c   

        self.SIGNAL = row.SIGNAL 
        self.TP = row.TP 
        self.SL = row.SL 
        self.result = 0.0 
        self.end_time = row.time
        self.start_time = row.time 
        self.duration = 0 

    def close_trade(self, row, result, trigger_price):
        self.running = False 
        self.result = result 
        self.end_time = row.time
        self.trigger_price = trigger_price


    def update(self, row):
        self.duration += 1 
        if self.SIGNAL == BUY:
            if row.bid_h >= self.TP:
                self.close_trade(row, PROFIT_FACTOR, row.bid_h)
            elif row.bid_l <= self.SL:
                self.close_trade(row, LOSS_FACTOR, row.bid_l)
             
        if self.SIGNAL == SELL:
            if row.ask_l <= self.TP:
                self.close_trade(row, PROFIT_FACTOR, row.ask_l)
            elif row.ask_h >= self.SL:
                self.close_trade(row, LOSS_FACTOR, row.ask_h)

In [55]:
open_trades = []
closed_trades = []

for index, row in df_slim.iterrows():
    for ot in open_trades:
        ot.update(row)
        if ot.running == False:
            closed_trades.append(ot)
    open_trades = [x for x in open_trades if x.running == True]

    if row.SIGNAL != NONE:
       open_trades.append(Trade(row))

In [56]:
vars(closed_trades[0])
df_result = pd.DataFrame.from_dict([vars(x) for x in closed_trades])
df_result.result.sum()

np.float64(-896.0)

In [57]:
df_result.sort_values(by="start_index", inplace=True)

In [58]:
df_m5 = pd.read_pickle("../data/EUR_USD_M5.pkl")

In [59]:
df_m5.shape

(713626, 14)

In [60]:
from dateutil import parser

In [61]:
df_m5_slim = df_m5[["time", "bid_h", "bid_l", "ask_h", "ask_l"]].copy()

In [62]:
df_m5_slim.head()

                       time    bid_h    bid_l    ask_h    ask_l
0 2015-06-01 00:00:00+00:00  1.09607  1.09548  1.09623  1.09564
1 2015-06-01 00:05:00+00:00  1.09620  1.09575  1.09636  1.09592
2 2015-06-01 00:10:00+00:00  1.09593  1.09546  1.09607  1.09563
3 2015-06-01 00:15:00+00:00  1.09574  1.09495  1.09593  1.09511
4 2015-06-01 00:20:00+00:00  1.09501  1.09367  1.09518  1.09384

In [63]:
df_signals = df_slim[df_slim.SIGNAL != NONE].copy()

In [64]:
df_signals["m5_start"] = [x + dt.timedelta(hours=1) for x in df_signals.time]

In [65]:
df_signals["start_index_h1"] = df_signals.index

In [66]:
df_signals.head()

,time,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,...,ask_c,ENGULFING,direction,EMA_50,RSI_14,SIGNAL,TP,SL,m5_start,start_index_h1
0,2015-06-03 01:00:00+00:00,1.11432,1.11754,1.11416,1.11745,1.11422,1.11746,1.11408,1.11738,1.11441,...,1.11752,True,1,1.104606,76.638276,1,1.12374,1.11441,2015-06-03 02:00:00+00:00,0
3,2015-06-03 04:00:00+00:00,1.11568,1.11738,1.11556,1.11627,1.11561,1.11730,1.11549,1.11620,1.11575,...,1.11634,True,1,1.106068,70.661109,1,1.11752,1.11575,2015-06-03 05:00:00+00:00,3
25,2015-06-04 02:00:00+00:00,1.12596,1.12691,1.12578,1.12660,1.12588,1.12684,1.12570,1.12653,1.12603,...,1.12666,True,1,1.116362,68.101812,1,1.12792,1.12603,2015-06-04 03:00:00+00:00,25
39,2015-06-04 16:00:00+00:00,1.12696,1.13184,1.12608,1.12878,1.12686,1.13175,1.12601,1.12869,1.12705,...,1.12887,True,1,1.122071,55.399618,1,1.13251,1.12705,2015-06-04 17:00:00+00:00,39
66,2015-06-05 19:00:00+00:00,1.11176,1.11194,1.11106,1.11113,1.11167,1.11186,1.11090,1.11104,1.11186,...,1.11122,True,-1,1.119360,35.822856,-1,1.10978,1.11167,2015-06-05 20:00:00+00:00,66

In [67]:
df_signals.columns

Index(['time', 'mid_o', 'mid_h', 'mid_l', 'mid_c', 'bid_o', 'bid_h', 'bid_l',
       'bid_c', 'ask_o', 'ask_h', 'ask_l', 'ask_c', 'ENGULFING', 'direction',
       'EMA_50', 'RSI_14', 'SIGNAL', 'TP', 'SL', 'm5_start', 'start_index_h1'],
      dtype='object')

In [69]:
df_signals.drop(['time', 'mid_o', 'mid_h', 'mid_l', 'mid_c','ask_h', 'bid_o', 'bid_h', 'bid_l', 'ask_o', 'ask_l','ENGULFING','EMA_50', 'RSI_14', "direction"], axis=1, inplace=True)

In [70]:
df_signals.head()

,bid_c,ask_c,SIGNAL,TP,SL,m5_start,start_index_h1
0,1.11738,1.11752,1,1.12374,1.11441,2015-06-03 02:00:00+00:00,0
3,1.11620,1.11634,1,1.11752,1.11575,2015-06-03 05:00:00+00:00,3
25,1.12653,1.12666,1,1.12792,1.12603,2015-06-04 03:00:00+00:00,25
39,1.12869,1.12887,1,1.13251,1.12705,2015-06-04 17:00:00+00:00,39
66,1.11104,1.11122,-1,1.10978,1.11167,2015-06-05 20:00:00+00:00,66

In [71]:
df_signals.rename(columns={
    "bid_c" : "start_price_BUY",
    "ask_c" : "start_price_SELL",
    "m5_start": "time"
}, inplace=True)

In [72]:
df_signals.head()

,start_price_BUY,start_price_SELL,SIGNAL,TP,SL,time,start_index_h1
0,1.11738,1.11752,1,1.12374,1.11441,2015-06-03 02:00:00+00:00,0
3,1.11620,1.11634,1,1.11752,1.11575,2015-06-03 05:00:00+00:00,3
25,1.12653,1.12666,1,1.12792,1.12603,2015-06-04 03:00:00+00:00,25
39,1.12869,1.12887,1,1.13251,1.12705,2015-06-04 17:00:00+00:00,39
66,1.11104,1.11122,-1,1.10978,1.11167,2015-06-05 20:00:00+00:00,66

In [73]:
df_m5_slim.head(2)

                       time    bid_h    bid_l    ask_h    ask_l
0 2015-06-01 00:00:00+00:00  1.09607  1.09548  1.09623  1.09564
1 2015-06-01 00:05:00+00:00  1.09620  1.09575  1.09636  1.09592

In [74]:
merged = pd.merge(left=df_m5_slim, right=df_signals, on="time", how="left")

In [75]:
merged[merged.SIGNAL.isna()==False].head()
merged.fillna(0, inplace=True)

In [76]:
merged.SIGNAL = merged.SIGNAL.astype(int)
merged.start_index_h1 = merged.start_index_h1.astype(int)

In [77]:
merged.head()

,time,bid_h,bid_l,ask_h,ask_l,start_price_BUY,start_price_SELL,SIGNAL,TP,SL,start_index_h1
0,2015-06-01 00:00:00+00:00,1.09607,1.09548,1.09623,1.09564,0.0,0.0,0,0.0,0.0,0
1,2015-06-01 00:05:00+00:00,1.09620,1.09575,1.09636,1.09592,0.0,0.0,0,0.0,0.0,0
2,2015-06-01 00:10:00+00:00,1.09593,1.09546,1.09607,1.09563,0.0,0.0,0,0.0,0.0,0
3,2015-06-01 00:15:00+00:00,1.09574,1.09495,1.09593,1.09511,0.0,0.0,0,0.0,0.0,0
4,2015-06-01 00:20:00+00:00,1.09501,1.09367,1.09518,1.09384,0.0,0.0,0,0.0,0.0,0

In [78]:
class TradeM5:
    def __init__(self, row):
        self.running = True
        self.start_index_m5 = row.name
        self.start_index_h1= row.start_index_h1

        if row.SIGNAL==BUY:

            self.start_price = row.start_price_BUY
            self.trigger_price = row.start_price_BUY
        else:
            self.start_price = row.start_price_SELL
            self.trigger_price = row.start_price_SELL
        #self.end_price = row.mid_c 
        self.SIGNAL = row.SIGNAL 
        self.TP = row.TP 
        self.SL = row.SL 
        self.result = 0.0 
        self.end_time = row.time
        self.start_time = row.time 
        self.duration = 1 

    def close_trade(self, row, result, trigger_price):
        self.running = False 
        self.result = result 
        self.end_time = row.time
        self.trigger_price = trigger_price


    def update(self, row):
        self.duration += 1 
        if self.SIGNAL == BUY:
            if row.bid_h >= self.TP:
                self.close_trade(row, PROFIT_FACTOR, row.bid_h)
            elif row.bid_l <= self.SL:
                self.close_trade(row, LOSS_FACTOR, row.bid_l)
             
        if self.SIGNAL == SELL:
            if row.ask_l <= self.TP:
                self.close_trade(row, PROFIT_FACTOR, row.ask_l)
            elif row.ask_h >= self.SL:
                self.close_trade(row, LOSS_FACTOR, row.ask_h)

In [79]:
open_trades_m5 = []
closed_trades_m5= []

for index, row in merged.iterrows():

    if row.SIGNAL != NONE:
       open_trades_m5.append(TradeM5(row))

    for ot in open_trades_m5:
        ot.update(row)
        if ot.running == False:
            closed_trades_m5.append(ot)
    open_trades_m5 = [x for x in open_trades_m5 if x.running == True]

In [80]:
df_res_m5 = pd.DataFrame.from_dict([vars(x) for x in closed_trades_m5])

In [81]:
df_res_m5.head()

,running,start_index_m5,start_index_h1,start_price,trigger_price,SIGNAL,TP,SL,result,end_time,start_time,duration
0,False,636,3,1.11620,1.11841,1,1.11752,1.11575,2.0,2015-06-03 05:05:00+00:00,2015-06-03 05:00:00+00:00,3
1,False,600,0,1.11738,1.11356,1,1.12374,1.11441,-1.0,2015-06-03 07:00:00+00:00,2015-06-03 02:00:00+00:00,62
2,False,900,25,1.12653,1.12602,1,1.12792,1.12603,-1.0,2015-06-04 06:00:00+00:00,2015-06-04 03:00:00+00:00,38
3,False,1068,39,1.12869,1.12635,1,1.13251,1.12705,-1.0,2015-06-04 17:35:00+00:00,2015-06-04 17:00:00+00:00,9
4,False,1392,66,1.11122,1.11171,-1,1.10978,1.11167,-1.0,2015-06-05 20:00:00+00:00,2015-06-05 20:00:00+00:00,2

In [82]:
df_res_m5.result.sum()

np.float64(-1788.0)

In [58]:
# with the spread attach to the trades